### ISSUE TITLE
Hod Icons 

### ISSUE THREAD

**Issue by jewelln** [eliothill/home-office-digital-patterns#1]
I have several icons that I need designed for Entity search.  The send a request link isn't working, on the icon pattern library page.  Should I make the icon request here?

Regards

Jewell

**Comment by eliothill** [comment]
Hi @jewelln I don't think we will be processing requests this way, sorry that content shouldn't have been there – if you could bring the work that this relates to on Monday to the IxD meeting then we can discuss what is required and the best way to work in the future, thanks.
